### PR TITLE
[IMP] Improved code to fix expected sigleton error when deleting user.

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**

### CODE REVIEW

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 Please add an update in the manifest with an explanation, since this may need to be fixed in v12 and v14 aswell.

**Comment by rupareliyahemangi145** [comment]
Ok sure Fredrik

**Review by nils-vertel — APPROVED** [review]

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Updated manifest file.

**Review by nils-vertel — APPROVED** [review]

**Review by iammiracle — APPROVED** [review]
Lets go to merge

**Pull request merged**
